import java.awt.Component;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Christopher
 */
public class vote extends javax.swing.JFrame {

    databaseConnect connection;
    
    /**
     * Creates new form logIn
     * @throws java.sql.SQLException
     */
    public vote() throws SQLException {
        
        ResultSet rs = null;
        
        try {
            connection = new databaseConnect();
            rs = connection.getCountries();
        } catch (SQLException ex) {
            Logger.getLogger(newUser.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        initComponents();
        
        
        while (rs.next()){
            twelveSlct.addItem(rs.getString("country"));
            tenSlct.addItem(rs.getString("country"));
            eightSlct.addItem(rs.getString("country"));
            sevenSlct.addItem(rs.getString("country"));
            sixSlct.addItem(rs.getString("country"));
            fiveSlct.addItem(rs.getString("country"));
            fourSlct.addItem(rs.getString("country"));
            threeSlct.addItem(rs.getString("country"));
            twoSlct.addItem(rs.getString("country"));
            oneSlct.addItem(rs.getString("country"));
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        twelveLbl = new javax.swing.JLabel();
        tenLbl = new javax.swing.JLabel();
        eightLbl = new javax.swing.JLabel();
        fiveLbl = new javax.swing.JLabel();
        sixlbl = new javax.swing.JLabel();
        sevenLbl = new javax.swing.JLabel();
        twelveSlct = new javax.swing.JComboBox<>();
        fiveSlct = new javax.swing.JComboBox<>();
        tenSlct = new javax.swing.JComboBox<>();
        fourSlct = new javax.swing.JComboBox<>();
        twoSlct = new javax.swing.JComboBox<>();
        sevenSlct = new javax.swing.JComboBox<>();
        eightSlct = new javax.swing.JComboBox<>();
        threeSlct = new javax.swing.JComboBox<>();
        sixSlct = new javax.swing.JComboBox<>();
        oneSlct = new javax.swing.JComboBox<>();
        fourLbl = new javax.swing.JLabel();
        threeLbl = new javax.swing.JLabel();
        twoLbl = new javax.swing.JLabel();
        oneLbl = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        jButton1.setText("jButton1");

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Eurovision Voter");

        twelveLbl.setText("Twelve Points");

        tenLbl.setText("Ten Points");

        eightLbl.setText("Eight Points");

        fiveLbl.setText("Five Points");

        sixlbl.setText("Six Points");

        sevenLbl.setText("Seven Points");

        twelveSlct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twelveSlctActionPerformed(evt);
            }
        });

        threeSlct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeSlctActionPerformed(evt);
            }
        });

        fourLbl.setText("Four Points");

        threeLbl.setText("Three Points");

        twoLbl.setText("Two Points");

        oneLbl.setText("One Point");

        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(eightLbl)
                    .addComponent(twelveLbl)
                    .addComponent(tenLbl)
                    .addComponent(sevenLbl)
                    .addComponent(sixlbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sixSlct, 0, 100, Short.MAX_VALUE)
                    .addComponent(sevenSlct, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eightSlct, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tenSlct, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(twelveSlct, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fiveLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fourLbl))
                        .addComponent(threeLbl))
                    .addComponent(twoLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(oneLbl, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(oneSlct, 0, 106, Short.MAX_VALUE)
                    .addComponent(twoSlct, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(threeSlct, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fourSlct, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fiveSlct, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(199, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(178, 178, 178))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(twelveLbl)
                    .addComponent(fiveLbl)
                    .addComponent(twelveSlct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fiveSlct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tenLbl)
                    .addComponent(tenSlct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fourSlct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fourLbl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eightLbl)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eightSlct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(threeSlct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(threeLbl))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(twoSlct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(twoLbl)
                            .addComponent(sevenSlct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sevenLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sixSlct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(oneSlct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(oneLbl)))
                    .addComponent(sixlbl))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void twelveSlctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twelveSlctActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_twelveSlctActionPerformed

    private void threeSlctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeSlctActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_threeSlctActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel eightLbl;
    private javax.swing.JComboBox<String> eightSlct;
    private javax.swing.JLabel fiveLbl;
    private javax.swing.JComboBox<String> fiveSlct;
    private javax.swing.JLabel fourLbl;
    private javax.swing.JComboBox<String> fourSlct;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel oneLbl;
    private javax.swing.JComboBox<String> oneSlct;
    private javax.swing.JLabel sevenLbl;
    private javax.swing.JComboBox<String> sevenSlct;
    private javax.swing.JComboBox<String> sixSlct;
    private javax.swing.JLabel sixlbl;
    private javax.swing.JLabel tenLbl;
    private javax.swing.JComboBox<String> tenSlct;
    private javax.swing.JLabel threeLbl;
    private javax.swing.JComboBox<String> threeSlct;
    private javax.swing.JLabel twelveLbl;
    private javax.swing.JComboBox<String> twelveSlct;
    private javax.swing.JLabel twoLbl;
    private javax.swing.JComboBox<String> twoSlct;
    // End of variables declaration//GEN-END:variables
}
